# Generated by Django 2.0.1 on 2018-01-06 21:42

from django.db import migrations, models
import src.apps.newsletter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dadosHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(max_length=80, null=True, unique=True, verbose_name='Título Principal')),
                ('subtitulo', models.CharField(max_length=80, verbose_name='Subtítulo')),
                ('texto', models.CharField(max_length=1500, verbose_name='Inclua o texto')),
            ],
            options={
                'verbose_name_plural': 'Dados da página principal',
                'verbose_name': 'Informação da página principal',
                'ordering': ['titulo_principal'],
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(height_field='image_height', upload_to=src.apps.newsletter.models.RandomFileName('landing_img'), verbose_name='Imagem do Carrossel', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dadoshome',
            name='imagens',
            field=models.ManyToManyField(related_name='imagens_carrossel', to='newsletter.Imagem'),
        ),
    ]
