# Generated by Django 2.0.1 on 2018-01-06 20:16

from django.db import migrations, models
import src.apps.newsletter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dadosHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=src.apps.newsletter.models.RandomFileName('landing_images'))),
                ('titulo_principal', models.CharField(max_length=80, null=True, unique=True, verbose_name='Título Principal')),
                ('subtitulo', models.CharField(max_length=80, verbose_name='Subtítulo')),
                ('texto', models.CharField(max_length=1500, verbose_name='Inclua o texto')),
            ],
            options={
                'ordering': ['titulo_principal'],
                'verbose_name': 'Informação da página principal',
                'verbose_name_plural': 'Dados da página principal',
            },
        ),
    ]
