# Generated by Django 2.0.1 on 2018-01-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagem',
            options={'ordering': ['imagem'], 'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens'},
        ),
    ]
