# Generated by Django 2.0.1 on 2018-01-06 20:30

from django.db import migrations, models
import src.apps.newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoshome',
            name='imagem',
            field=models.ImageField(upload_to=src.apps.newsletter.models.RandomFileName('media/landing_img')),
        ),
    ]
