# Generated by Django 2.0.1 on 2018-01-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20180107_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoshome',
            name='inscreva',
            field=models.CharField(default=1, max_length=30, verbose_name='Apelo chamativo para o usuário se inscrever'),
            preserve_default=False,
        ),
    ]
