# Generated by Django 2.0.1 on 2018-01-07 00:14

from django.db import migrations, models
import src.apps.newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20180106_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(height_field='image_height', unique=True, upload_to=src.apps.newsletter.models.RandomFileName('landing_img'), verbose_name='Imagem do Carrossel', width_field='image_width'),
        ),
    ]
