# Generated by Django 2.0.1 on 2018-01-07 14:59

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_dadoshome_inscreva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoshome',
            name='texto',
            field=froala_editor.fields.FroalaField(max_length=1500, verbose_name='Texto'),
        ),
    ]
