# Generated by Django 2.0.1 on 2018-01-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20180106_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoshome',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
