# Generated by Django 2.0.1 on 2018-01-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_dadoshome_data_modificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
